### ISSUE TITLE
Expose tracker flag

### ISSUE THREAD

**Issue by vRobM** [anacrolix/cove#12]
As requested to support private/public trackers, ideally the flag supports a list of trackers from a tracker file.

It would be nice to pick up trackers into a working list from the torrents/magnets from the UI, not only DHT. (let me know if this needs a new issue)

**Comment by anacrolix** [comment]
I'll add a flag to add implicit trackers to all torrents. At the moment if you enter a magnet link in the search bar that contains trackers, those should already be used. You are correct that DHT search results should not currently use any trackers (other than the DHT).

**Comment by vRobM** [comment]
I noticed the search results never include tracker results. 
So newly published torrents take 1-2 days to appear in DHT which is disappointingly long.

**Comment by vRobM** [comment]
I have an expectation to see discovery for hashes/magnets/trackers that were input myself. 

w/o that, I understand, DHT is all there is.

**Comment by anacrolix** [comment]
This will be in the next release as `-implicitTracker`, which you can repeat for each tracker.

**Comment by vRobM** [comment]
does that mean UI inputs will add implicit trackers if present?

**Comment by vRobM** [comment]
This needs a default value so it doesn't fail launching w/o params

0.0.8 had this right

**Comment by anacrolix** [comment]
I'm not sure what you mean. How is failing to launch?

**Comment by vRobM** [comment]
-implicitTracker expects a value and errors w/o it failing to start cove

**Comment by anacrolix** [comment]
`-implicitTracker=url`?

**Comment by vRobM** [comment]
no url value = error on startup (0.0.8 had default values if one wasn't provided)

udp://, tcp:// and http:// don't fail startup but I can't tell if they work or if scrapes happen

**Comment by anacrolix** [comment]
If you use the flag you must provide a url.
