### ISSUE TITLE
search broken in 0.0.11

### ISSUE THREAD

**Issue by vRobM** [anacrolix/cove#13]
attempting any search, red error msg shows

```
[2023-09-11 18:27:53 +0000 NIL] search for "synduality" by "cove" returned error after 187.098583ms: all search backends failed [github.com/anacrolix/webtorrent handlers.go:1366]
```

no magnet links loaded either, just spun waiting

was this tested?

**Comment by anacrolix** [comment]
You need to wait a while for the DHT indexer to do its thing. You should reuse the directory you had for previous versions to pick up where the indexer left off.

**Comment by vRobM** [comment]
you're right, it worked a bit later, although inputting a magnet link with trackers doesn't seem to help find the hash

**Comment by anacrolix** [comment]
Thanks, I've documented this at https://coveapp info.
