### ISSUE TITLE
Large transcodes don't get cached

### ISSUE THREAD

**Issue by anacrolix** [anacrolix/cove#15]
Transcodes that are larger than 1GB will fail to cache (in the dev build), and be restarted in a loop.

**Comment by a52948** [comment]
To be honest, I didn't want it to cache on the server, which would take up a lot of space.

**Comment by anacrolix** [comment]
Unfortunately it's a requirement for streaming directly to browsers using HTTP range requests for video sources. There are other ways to do it but they require custom players on the client side. 

Per the other issue I'll make transcoding previews optional.

**Comment by anacrolix** [comment]
Fixed
