### ISSUE TITLE
Missing download options in browse screens

### ISSUE THREAD

**Issue by vRobM** [anacrolix/cove#16]
When exploring a search result, one may find portions or all of the item is desirable for download via magnet or torrent file, but those options are missing there.

Downloads via the current options are not reliable and timeout often with no resuming. Hence the need for queuing them up in a torrent client.

Alternatively, add a download manager interface where this can be managed from within cove.

**Comment by anacrolix** [comment]
cove intentionally only provides streaming access to files. It's not intended to be a regular torrent client. You should stream the files out to disk individually, or make use of the ZIP button or something similar.

Is the infohash as shown not enough to work with a regular BitTorrent client? Do you have some examples of the unreliability or timeouts? How many concurrent downloads are you doing when you get those?

**Comment by vRobM** [comment]
I get it, but it's also about discovery. You don't know you might want to download a whole season of a show lets say, until you see a few EPs. Then you want to get them all. Not as a zip but as the original package you were browsing.

By simply having the links for convenience, you offload those functions to things people already have and free up the concurrency of cove to deal with other things it's actually good at.

No the infohash is not enough because it doesn't help get the files to the torrent client. A magnet link is needed at least. Which is why it's also helpful to save the trackers from the magnet links one pastes in for obvious reasons down the line (peers).

As for examples, yes plenty. Let's say you have a torrent full of images or PDFs, which you want to sample/stream, so you click into each one, and you have to wait until each downloads which makes for a poor browsing experience. 

From there I open multiple tabs and click into the next one while the previous is still loading so I don't have to wait as long. This runs into the concurrency issue and many crashes, which further delays everything.

If you can make sure cove doesn't crash with concurrent downloads, that would be a big help.
