### ISSUE TITLE
Failed to start auto-boot at boot

### ISSUE THREAD

**Issue by a52948** [anacrolix/cove#21]
Under linux, I wrote it into the boot service of the system. Through "systemctl start cove" and "systemctl enable cove", let it boot up automatically, but after using it a few times, it will fail to boot every time it is booted, but if you clear the "ledis" folder, it will work normally.

**Comment by anacrolix** [comment]
Could you provide the error message or panic backtrace you are seeing?

**Comment by anacrolix** [comment]
I think this was fixed in a newer version.
