### ISSUE TITLE
Indexing takes a while to be comprehensive

### ISSUE THREAD

**Issue by AkliOnet** [anacrolix/cove#24]
i just installed and tested the search. how many time it's supposed to take to have "a good  index" ?

**Comment by anacrolix** [comment]
A few days and I find the index to be pretty good. Obviously I have a long-lived development one that is really really comprehensive, that takes a few weeks. Once you have a good index it maintains itself with very little use. Here's some more information https://www.coveapp.info/OPERATION#dht-indexing.
