### ISSUE TITLE
Please ship libpossum.so ?

### ISSUE THREAD

**Issue by amaumene** [anacrolix/cove#26]
Hi,

On the latest release I hit:
```./cove: error while loading shared libraries: libpossum.so: cannot open shared object file: No such file or directory```

I gave a try to building libpossum but I encountered various issues (some probably due to my oldish rust toolchain) and I was wondering if you plan to ship libpossum.so? Or maybe release a version of cove not linked against it for people who don't want to use it?

Thanks in advance.

**Comment by anacrolix** [comment]
Thanks for reporting this, I must have completely missed it. I'll statically link it in the next release.

**Comment by anacrolix** [comment]
@amaumene which platform were you using? I have reproduced this for darwin, and I'm guessing it's broken on Linux builds but I'm not sure which ones.

**Comment by amaumene** [comment]
Hi,

I tried Linux amd64. By the way I know have this message when I try to start cove:
```
[2024-02-09 09:44:02 +0900 CRT cove main.go:76]
  Application expiry has been exceeded. Update the application.
[2024-02-09 09:44:02 +0900 NIL github.com/anacrolix/gostdapp app.go:39]
  error in main: application expiry exceeded
```
Is it related?

**Comment by anacrolix** [comment]
@amaumene Please try https://github.com/anacrolix/cove/releases/tag/v0.4.2. Full changelog coming.

**Comment by anacrolix** [comment]
This should be fixed now.
