### ISSUE TITLE
Page showing random characters

### ISSUE THREAD

**Issue by Mntz** [anacrolix/cove#27]
I tried running Cove headless under Ubuntu Server 20.04.6 but when visiting http://hostname:8080 some random characters are returned. Like something is wrong with encryption or encoding.

The server is proxied through Cloudflare but disabling this didn't seem to help.
According to the logs, the service is running fine and is finding new torrents.

Any idea what could cause this?

![cove](https://github.com/anacrolix/cove/assets/3694374/4347f815-035c-4dd5-babb-b0f1d030d37b)

**Comment by anacrolix** [comment]
Oh wow, that's interesting. It looks like compression is being applied. It's very likely caused by CloudFlare or your browser. Are you able to connect directly to the instance and rule out CloudFlare?

**Comment by anacrolix** [comment]
Sorry I just saw you've already tried disabling it. It might be incorrect or unsupported compression in cove. What browser and version are you using?

**Comment by anacrolix** [comment]
I believe I identified the problem. Please try https://github.com/anacrolix/cove/releases/tag/v0.4.8.

**Comment by Mntz** [comment]
That's great, the new version fixed it.
Thanks for this awesome software!

**Comment by anacrolix** [comment]
Thanks!
