### ISSUE TITLE
can not run this

### ISSUE THREAD

**Issue by qkkas** [anacrolix/cove#31]
there is an SQLITE error,and I can not use this

![屏幕截图 2024-08-21 235308](https://github.com/user-attachments/assets/75cb5abc-1645-4c52-8670-73b337857b2b)

**Comment by qkkas** [comment]
and the cove app can not run on android 13,it only runs on some erlier andrroid version

**Comment by anacrolix** [comment]
Thanks for the report. The startup issue may have been fixed in v0.4.9. What version are you using?

Could you check if that directory, after the `file:` exists on your system?

**Comment by qkkas** [comment]
oh no,I use v0.4.10,and the file never exists

**Comment by anacrolix** [comment]
Could you check specifically if the directory C:\Users\qkkas\AppData\Roaming\cove exists?

**Comment by qkkas** [comment]
yes there is this file

**Comment by qkkas** [comment]
And the app can not run on my miui android 13 device

**Comment by qkkas** [comment]
Is there any log I can give you to solve the problem?

**Comment by anacrolix** [comment]
Yes, on windows you can send me cove.log. I'm not sure it will help based on the above message, I'll probably need to reproduce it on Windows. It's very likely a file permission access problem, maybe caused by anti virus or just weird Unix incompatibilities.

**Comment by qkkas** [comment]
I know a little about that.It looks like that the program can't read the SQLITE file.But sadly I only use Windows Defender.And I do not know how to find the log file.Also,I want to ask how can I add trackers to the torrents?Do the program support PEX or LSD?（Sometimes I use qbittorent and get a nice speed but this program is slow.）

**Comment by qkkas** [comment]
I never run the program in zip file.I use it after unzip the file.And I think LSD can increase the speed so I advocate for this feature.And there are many bugs/feedback I want to tell you.Do you have time to solve them?

**Comment by qkkas** [comment]
An addition problem (maybe a little not related to the question) is that I am not a native English speaker,so there will be some grammar errors and misunding in my feedback :).And I wamt to ask if my English is good?/Is there any wrong disturbing you?Finally,thanks to all your work.₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by anacrolix** [comment]
Yes, please comment them here or open new issues

**Comment by anacrolix** [comment]
Yes, unfortunately. It's not trivial to test for Windows for me. I haven't see this issue.

**Comment by qkkas** [comment]
What about your Windows version?And where can I get the log of cove?

**Comment by qkkas** [comment]
And I can use v4.0.9,there's no this problem.But I can't use 4.0.10,there's a set-up problem

**Comment by qkkas** [comment]
I test this program on two windows devices,both the two devices encounter the same problem.

**Comment by qkkas** [comment]
I have updated my Windows, and this problem is solved.Thanks for your work！

**Comment by qkkas** [comment]
close
