### ISSUE TITLE
application can not ru on higher android

### ISSUE THREAD

**Issue by qkkas** [anacrolix/cove#32]
the application can only run on the system based on Android SDK 16-16, it can not run on my miui Android 13 device.

**Comment by anacrolix** [comment]
It uses Android API 33. https://apilevels.com/. I should be able to go back as far as 21, but I'm not sure that will help.

**Comment by qkkas** [comment]
![Uploading Screenshot_2024-08-27-15-07-06-017_com.miui.securitycenter-edit.jpg…]()
my system says the target sdk version is 16

**Comment by qkkas** [comment]
![Screenshot_2024-08-27-15-07-06-017_com miui securitycenter-edit](https://github.com/user-attachments/assets/7c34ad6f-ad3e-4090-a27d-6a33498145c2)
my system says the target sdk version is 16

**Comment by qkkas** [comment]
it crashes for many times,higher android version can't use

**Comment by anacrolix** [comment]
![image](https://github.com/user-attachments/assets/c83d9a27-cc67-422b-8395-b7a15ff8761b)

**Comment by qkkas** [comment]
thaks for your work i will close this issue.

**Comment by anacrolix** [comment]
This change will be included in the next release of cove https://www.coveapp.info/CHANGELOG.
