### ISSUE TITLE
Application expiry exceeded

### ISSUE THREAD

**Issue by Photopuppet** [anacrolix/cove#35]
Dear Anacrolix,

Cove suddenly crashed out on Windows and I now keep getting the following error message even with a fresh installation:

[2024-11-02 14:40:18 +0000 CRT cove main.go:248]
  Application expiry has been exceeded. Update the application.
[2024-11-02 14:41:43 +0000 NIL github.com/anacrolix/gostdapp app.go:40]
  error in main: application expiry exceeded

Many thanks for any help you can offer!

**Comment by anacrolix** [comment]
What version of cove are you using?

**Comment by Photopuppet** [comment]
The latest release for Windows - v0.4.10

Thank you!

**Comment by anacrolix** [comment]
Cheers, I'll make a new release soon

**Comment by Photopuppet** [comment]
Thanks Matt, very much appreciated 👍 Any idea why it has a time limit in
the first place? To stop people using old versions for too long?

**Comment by anacrolix** [comment]
Yeah sorry for the delay. I wanted to keep momentum going and I was never sure what my contribution process (as in a fee or subscription or something) would be. I've extended it to 1 year for the next release, which I'm about to make. https://github.com/anacrolix/cove/wiki/CHANGELOG#v050

**Comment by anacrolix** [comment]
New release is out

**Comment by outer2H** [comment]
hi, it's still the same for docker:

```
> cove  | [2024-12-30 10:54:52 +0000 CRT cove main.go:287]
> cove  |   msg="Application expiry has been exceeded. Update the application."
> cove  | [2024-12-30 10:54:57 +0000 CRT github.com/anacrolix/gostdapp app.go:47]
> cove  |   msg="error in main: application expiry exceeded"
```
