### ISSUE TITLE
error in main: initializing local DHT indexer

### ISSUE THREAD

**Issue by Mntz** [anacrolix/cove#37]
I removed my old cove install and wanted to start from scratch with the latest version but I'm seeing the below error when trying to run cove. OS is Ubuntu Server 20.04.6 LTS.

[2024-12-27 15:39:13 +0100 CRT github.com/anacrolix/gostdapp app.go:47]
  msg="error in main: initializing local DHT indexer: creating search conn factory: opening caterwaul db: pebble: merger name from file \"dht-indexer-bitmap-merger\" != merger name from options \"caterwaul-merger\""

**Comment by anacrolix** [comment]
You'll need to clear the cove cache dir, it should be ~/.local/cache/cove on Linux or something like that. Or you can run with -workDir which keeps all data in the working directory.

**Comment by Mntz** [comment]
Thanks, got it working again!

**Comment by anacrolix** [comment]
Fantastic, thanks for following up.
