### ISSUE TITLE
Add AUR installation instructions to documentation

### ISSUE THREAD

**Issue by weebney** [anacrolix/cove#6]
Cove is now available for Arch Linux via the Arch User Repository (AUR). It's in the repo as [`cove`](https://aur.archlinux.org/packages/cove) and can be installed with:

```console
$ yay -S cove
```

Would be worth adding this to the installation instructions page.

**Comment by anacrolix** [comment]
Thanks, will do.

**Comment by anacrolix** [comment]
https://www.coveapp.info/INSTALL#arch-linux

**Comment by anacrolix** [comment]
I think this package may need to be updated.

**Comment by anacrolix** [comment]
Sweet, thx
